// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeviSI6VfGJuEwffxNFuTmvS5p4zjYfZM',
    appId: '1:289380627307:web:5d95c73b01c1b59f7ad22e',
    messagingSenderId: '289380627307',
    projectId: 'finanzas-pareja-123bf',
    authDomain: 'finanzas-pareja-123bf.firebaseapp.com',
    storageBucket: 'finanzas-pareja-123bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJlWikzdNLEu2m5_N6gl-Q0LrBV4gSGxc',
    appId: '1:289380627307:android:441a9da4926128d87ad22e',
    messagingSenderId: '289380627307',
    projectId: 'finanzas-pareja-123bf',
    storageBucket: 'finanzas-pareja-123bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuBgWxALAnnMSgwElUuvjEolmVyAjit2o',
    appId: '1:289380627307:ios:e3629f51a1e4b1357ad22e',
    messagingSenderId: '289380627307',
    projectId: 'finanzas-pareja-123bf',
    storageBucket: 'finanzas-pareja-123bf.firebasestorage.app',
    iosClientId: '289380627307-11k25tfauvicvlgkhh28lbcf0esdp0iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinanzas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuBgWxALAnnMSgwElUuvjEolmVyAjit2o',
    appId: '1:289380627307:ios:e3629f51a1e4b1357ad22e',
    messagingSenderId: '289380627307',
    projectId: 'finanzas-pareja-123bf',
    storageBucket: 'finanzas-pareja-123bf.firebasestorage.app',
    iosClientId: '289380627307-11k25tfauvicvlgkhh28lbcf0esdp0iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinanzas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeviSI6VfGJuEwffxNFuTmvS5p4zjYfZM',
    appId: '1:289380627307:web:6d9b089354ef244b7ad22e',
    messagingSenderId: '289380627307',
    projectId: 'finanzas-pareja-123bf',
    authDomain: 'finanzas-pareja-123bf.firebaseapp.com',
    storageBucket: 'finanzas-pareja-123bf.firebasestorage.app',
  );
}
